In [1]:
import pyodbc
import pandas

In [10]:
from datetime import datetime, date
import re
import sys

import pyodbc
cnxn = pyodbc.connect("DRIVER={ODBC Driver 17 for SQL Server};SERVER=edhazurencertdmgbprod.database.windows.net;PORT=1433;DATABASE=edhazurencertdmgbprod;UID=BOT_PMI_PaymentPlanEUR@ab-inbev.com;PWD=3]TF9+T7mqa5_\j,[F+3nY{z7@'n3m[};AUTHENTICATION=ActiveDirectoryPassword")

In [3]:
cursor = cnxn.cursor()
cursor.execute("SELECT lifnr, adrnr FROM [abi_compliance_control_europe_non_sensitive_rpt].[lfa1] WHERE lifnr = '0000346942'") 
row = cursor.fetchone()
while row: 
    print(row)
    row = cursor.fetchone()

SystemError: <class 'pyodbc.Error'> returned a result with an error set

In [ ]:
cursor = cnxn.cursor()
cursor.execute("SELECT * FROM [abi_compliance_control_europe_non_sensitive_rpt].[bsik] WHERE lifnr = '0000381111'") 
row = cursor.fetchone()
while row: 
    print(row[8])
    row = cursor.fetchone()

In [268]:
cursor = cnxn.cursor()
cursor.execute("SELECT TOP(100) * FROM [abi_compliance_control_europe_non_sensitive_rpt].[vbkpf] WHERE bukrs = '5100000635'") 
row = cursor.fetchone()
while row: 
    print(row)
    row = cursor.fetchone()

OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x36 (54) (SQLExecDirectW)')

In [3]:
sql = "SELECT bukrs, belnr, bstat, blart FROM [abi_compliance_control_europe_non_sensitive_rpt].[vbkpf] WHERE bukrs = 'FR11'"
data = pandas.read_sql(sql,cnxn)

In [ ]:
l1 = list(data['belnr'])

In [3]:
sql = "SELECT bukrs, belnr, bstat, blart FROM [abi_compliance_control_europe_non_sensitive_rpt].[bkpf] WHERE bukrs = 'FR11'"
data1 = pandas.read_sql(sql,cnxn)

In [ ]:
l2 = list(data1[data1['bstat'] == 'V']['belnr'])

l3 = [i for i in l1 if i not in l2]

In [ ]:
len(l3)

In [ ]:
data1[data1['bstat'] == 'V']

In [ ]:
sql = "SELECT bukrs, belnr, blart FROM [abi_compliance_control_europe_non_sensitive_rpt].[vbsegs] WHERE bukrs = 'FR11'"
data2 = pandas.read_sql(sql,cnxn)

In [11]:
sql = "SELECT bukrs, belnr, bstat, blart, lifnr FROM [abi_compliance_control_europe_non_sensitive_rpt].[bsik]"
data2 = pandas.read_sql(sql,cnxn)

In [4]:
cursor = cnxn.cursor()
cursor.execute(sql) 
row = cursor.fetchone()
while row: 
    print(row)
    row = cursor.fetchone()
    break

OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x36 (54) (SQLExecDirectW)')

In [ ]:
sql = "select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME='bsik'"
data2 = pandas.read_sql(sql,cnxn)
data2[data2['TABLE_SCHEMA'] == 'abi_compliance_control_europe_non_sensitive_rpt']['COLUMN_NAME']

In [11]:
data2.bstat.unique()

array(['', 'S'], dtype=object)

In [12]:
sql = "SELECT bukrs, belnr, bstat, blart FROM [abi_compliance_control_europe_non_sensitive_rpt].[vbkpf]"
data3 = pandas.read_sql(sql,cnxn)

In [16]:
df3 = pandas.merge(data2, data3, how='inner', on='belnr')

In [14]:
data2

       bukrs       belnr bstat blart       lifnr
0       BE11  5100020781          YE  0000300395
1       BE11  5100022616          RE  0000000525
2       BE11  5100025439          RE  0000300270
3       BE11  5100057975          RE  0000000186
4       BE11  5100046226          RE  0000000186
...      ...         ...   ...   ...         ...
267653  RO11  1200024866          SB  0090006890
267654  UA01  5112909955          RE  0003011484
267655  RU14  5112986219          RE  0000341675
267656  BE11  5100013656          RE  0000328708
267657  BE11  5100036280          RE  0000369645

[267658 rows x 5 columns]

In [17]:
df3

       bukrs_x       belnr bstat_x blart_x       lifnr bukrs_y bstat_y blart_y
0         BE11  5100020781              YE  0000300395    DE11       V      YE
1         GB11  5100020781              YE  0003000222    DE11       V      YE
2         BE11  5100025439              RE  0000300270    GB11       V      YE
3         BE11  5100046226              RE  0000000186    GB11       V      YE
4         BE11  5100018774              RE  0000000186    NL11       V      YE
...        ...         ...     ...     ...         ...     ...     ...     ...
125348    GB11  5100095314              RE  0000378436    BE11       V      YE
125349    BE11  5100035861              RE  0000000525    GB11       V      YE
125350    BE11  5100019239              RE  0000000525    GB11       V      YE
125351    RU14  5112986219              RE  0000341675    RU14       V      RE
125352    BE11  5100036280              RE  0000369645    GB11       V      RE

[125353 rows x 8 columns]

In [7]:
sql = "SELECT name1, lifnr FROM [abi_compliance_control_europe_non_sensitive_rpt].[lfa1]"
data4 = pandas.read_sql(sql,cnxn)

In [8]:
data4

                                      name1       lifnr
0           TOV AVP Nordik Prodakts Ukraine  0000308473
1       Uchebniy tcentr №8 sluzbi transport  0000308523
2       UPRAVLINNYA DERJAVNOI KAZNACHEYSKOI  0000308524
3            UPF v Goloseevskom r-ne g.Kiev  0000308525
4                               CHP "ANVIT"  0000308526
...                                     ...         ...
178712            Landeshauptstadt Hannover  0000361620
178713                    Signal Iduna/NOVA  0000361621
178714                        Block 17 e.V.  0000361622
178715                  HEVO VERTRIEBS GMBH  0000374797
178716                        CARL SCHLÜTER  0000374810

[178717 rows x 2 columns]

In [12]:
data2

       bukrs       belnr bstat blart       lifnr
0       BE11  5100020781          YE  0000300395
1       BE11  5100022616          RE  0000000525
2       BE11  5100025439          RE  0000300270
3       BE11  5100057975          RE  0000000186
4       BE11  5100046226          RE  0000000186
...      ...         ...   ...   ...         ...
267653  RO11  1200024866          SB  0090006890
267654  UA01  5112909955          RE  0003011484
267655  RU14  5112986219          RE  0000341675
267656  BE11  5100013656          RE  0000328708
267657  BE11  5100036280          RE  0000369645

[267658 rows x 5 columns]

In [95]:
import subprocess
p = subprocess.Popen(["python","test.py"],stdin=PIPE,stdout=PIPE)
p.wait()
print(p.poll())

5

In [96]:
from subprocess import PIPE, Popen

In [83]:
p.communicate()

(b'', None)

In [86]:
print(p.poll())

1

In [246]:
import os
import smtplib
import keyring
from openpyxl import load_workbook
folder_location = '/Users/vsquareg/AbInBev'
fbl1n_file_name = os.path.join(folder_location, '0000381111_raw.xlsx')
save_file_name = os.path.join(folder_location, '0000381111_final.xlsx')
log_file_name = os.path.join(folder_location, '0000381111_log.txt')
vendor_id = '0000381111'
vendor_type = 4
pc_codes_file = os.path.join(folder_location, 'pc_codes.xlsx')
euz_scheduled_run_file = os.path.join(folder_location, 'EUZ_Scheduled_Run.xlsx')
vim_file_name = os.path.join(folder_location, 'VIM_Analytics_381111.xlsx')
vendor_name = 'ADM Spain'
vendor_email_address = os.path.join(folder_location, 'vaibhav.vardhan@ab-inbev.com')

In [247]:
class Email:
    def __init__(self):
        self.client = smtplib.SMTP('smtp.gmail.com', 587)
  
        # start TLS for security
        self.client.starttls()

        # Authentication
        self.client.login("incupton@gmail.com", keyring.get_password('test_email', 'inc.upton@gmail.com'))

        self.from_email = "inc.upton@gmail.com"
        
    def send_email(self, to, subject, body, attachment = None):
        msg = MIMEMultipart()
        msg['From'] = self.from_email
        msg['To'] = to
        msg['Date'] = formatdate(localtime = True)
        msg['Subject'] = subject
        msg.attach(MIMEText(body))

        if attachment:
            fp = open(attachment, 'rb')
            part = MIMEBase('application','vnd.ms-excel')
            part.set_payload(fp.read())
            fp.close()
            encoders.encode_base64(part)
            part.add_header('Content-Disposition', 'attachment', filename=os.path.basename(attachment))
            msg.attach(part)

        self.client.sendmail(self.from_email, to, msg.as_string())

    def __del__(self):
        try:
            self.client.quit()
        except:
            pass
    
        
class Logger:
    def __init__(self, log_file_name, vendor_id):
        self.file = open(log_file_name, "a")
        self.vendor_id = vendor_id

    def add_log(self, err):
        self.file.write(' [ Execution for vendor ID: ' + str(self.vendor_id) + ' failed. ' + err + '] ')

    def __del__(self):
        self.file.close()

def process_ref_key(tmp):
    if not numpy.isnan(tmp):
        return int(tmp/10000)
    return tmp

def get(ws, col_name, row, value = True):
    if value:
        return ws.cell(row = row, column = columns[col_name]).value
    return ws.cell(row = row, column = columns[col_name])

def put(ws, col_name, row, val):
    ws.cell(row = row, column = columns[col_name]).value = val

def extract_PC_codes(pc_codes_file):
   workbook = load_workbook(filename=pc_codes_file)
   ws = workbook[workbook.sheetnames[0]]
   for row in ws.iter_rows(min_row = 2):
       pc_actions[row[0].value] = row[3].value
       pc_comments[row[0].value] = row[1].value

def handle_datetime(val):
    if 'datetime' not in str(type(val)):
        val = datetime.strptime(val, '%m/%d/%Y')
    return val
    
def extract_scheduled_dates(euz_scheduled_run_file):
    workbook = load_workbook(filename=euz_scheduled_run_file)
    ws = workbook[workbook.sheetnames[0]]
    for row in ws.iter_rows(min_row = 2):
        payment_dates.append(handle_datetime(row[0].value))
        cutoff_dates.append(handle_datetime(row[1].value))

def get_scheduled_date(baseline_date, vendor_type = 1):
    row_num = 12
    lowest_delta = 357
    scheduled_date = payment_dates[0]
    if vendor_type == 1:
        row_num = 12
    elif vendor_type == 2:
        row_num = 24
    elif vendor_type == 4:
        row_num = 48
    
    for row in range(row_num):
        now_delta = (payment_dates[row] - datetime.now()).days
        posting_delta = (cutoff_dates[row] - baseline_date).days
        # print(payment_dates[row], baseline_date, now_delta, posting_delta)
        if now_delta >= 0 and now_delta < lowest_delta and posting_delta >= 0:
            scheduled_date = payment_dates[row]
            lowest_delta = now_delta
    
    return scheduled_date.date()

def process_ip_number(x):
    if numpy.isnan(x['Purch.Doc.']):
        return float('nan')
    if numpy.isnan(x['Old DocNum']):
        return x['DocumentNo_y']
    else:
        return x['Old DocNum']
    

col_names = ['VendorName', 'VendorID', 'Status', 'DocType', 'CompanyCode', 'DocumentNo', 'Reference',
    'PaymentBlock', 'NetDueDate', 'PaymentTerms', 'Currency', 'Text', 'TXCode', 'PCAmount', 'LCAmount', 'BaselineDate', 'ReferenceKey',
    'Comment', 'ActionRequired', 'ScheduledDate']

col_names = ['VendorID', 'PaymentBlock', 'DocType', 'CompanyCode', 'DocumentNo', 'Reference', 'PaymentTerms', \
             'Credit/Debit', 'LCAmount', 'Currency', 'TXCode', 'Text', 'BaselineDate', 'Status_V', 'Status', \
             'ReferenceKey', 'Comment', 'ActionRequired', 'ScheduledDate']

doctype = {
    'YE': 'Basware type',
    'RE': 'B2B/PDF',
    'KG': 'FI Credit Note',
    'KR': 'Credit Note',
    }

In [248]:
columns = {}
pc_actions = {}
pc_comments = {}
payment_dates = []
cutoff_dates = []

balance = {}


logger = Logger(log_file_name, vendor_id)
email_handler = Email()

import time
start = time.time()

for i, col in enumerate(col_names):
    columns[col] = i+1

try:
    extract_PC_codes(pc_codes_file)
except:
    logger.add_log('Unable to extract PC codes.')
    raise

try:
    extract_scheduled_dates(euz_scheduled_run_file)
except:
    logger.add_log('Unable to extract EUZ_Scheduled_Run')
    raise

begin_row = 1
begin_col = 1

try:
    workbook = load_workbook(filename=fbl1n_file_name)
    ws = workbook[workbook.sheetnames[0]]
except:
    logger.add_log('Unable to load VendorLine file.')
    raise

row_count = ws.max_row
# row_count = 40

In [249]:
for row in range(2, row_count + 1):
    
    # document type
    try:
        if curr_doc_type:= get(ws, 'DocType', row):
            put(ws, 'DocType', row, doctype[curr_doc_type])
    except:
        pass

    parked = False
    if get(ws, 'Status', row) == 'Parked':
        parked = True

    # payment block
    if get(ws, 'PaymentBlock', row):
        #TODO: add status check
        put(ws, 'Status', row, 'Blocked for ***')

    # mapping PC codes to comments/actions
    if text_str:= get(ws, 'Text', row):
        if pc_search:=re.search(r'(PC)\d\d',str(text_str)):
            pc_action = pc_actions[pc_search[0].upper()]
            pc_comment = pc_comments[pc_search[0].upper()]
            put(ws, 'Comment', row, pc_comment)
            put(ws, 'ActionRequired', row, pc_action)

    # getting scheduled date for non-parked items
    if not parked:
        try:
            if baseline_date:= get(ws, 'BaselineDate', row):
#                 baseline_date = datetime.strptime(baseline_date, '%d.%m.%Y')
                scheduled_date = get_scheduled_date(baseline_date, vendor_type)
                put(ws, 'ScheduledDate', row, scheduled_date)

                # update total balance for scheduled date
                amount_sgn = get(ws, 'Credit/Debit', row)
                amount = get(ws, 'LCAmount', row)
                
                if amount_sgn == 'H':
                    amount *= -1
#                 amount = get(ws, 'LCAmount', row).split(',')
#                 if len(amount) > 1:
#                     amount = float(amount[0].replace('.', '') + '.' + amount[1])
#                 else:
#                     amount = float(amount[0].replace('.', ''))
                balance[scheduled_date] = balance.get(scheduled_date, 0) + amount
        except Exception as e:
                print(e)
                put(ws, 'ScheduledDate', row, '')
    else:
        put(ws, 'ScheduledDate', row, '')

# debit-balance check; if debit balance, update status and scheduled date
for row in range(2, row_count + 1):
    if balance.get(get(ws, 'ScheduledDate', row), -1) >= 0:
        put(ws, 'Status', row, 'Debit balance')
        put(ws, 'ScheduledDate', row, '')

# rename columns
for col in col_names:
    put(ws, col, 1, col)

# delete unnecessary columns
# to_delete = ['ReferenceKey', 'BaselineDate', 'PCAmount', 'Text','PaymentBlock']
to_delete = ['Status_V', 'Text', 'PaymentBlock']

for col in to_delete:
    ws.delete_cols(columns[col], 1)

try:
    workbook.save(filename = save_file_name)
except:
    logger.add_log('Unable to save modified VendorLine file.')

In [281]:
from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.sharepoint.client_context import ClientContext
from office365.sharepoint.files.file import File

url = 'https://anheuserbuschinbev.sharepoint.com/sites/PaymentPlanEUR/'
username = 'BOT_PMI_PaymentPlanEUR@ab-inbev.com'
password = "3]TF9+T7mqa5_\j,[F+3nY{z7@'n3m[}"
relative_url = '/sites/PaymentPlanEUR/Shared%20Documents/Inputs/pc_codes.xlsx'

In [ ]:
ctx_auth = AuthenticationContext(url)
ctx_auth.acquire_token_for_user(username, password)   
ctx = ClientContext(url, ctx_auth)
response = File.open_binary(ctx, "/Shared Documents/User Guide.docx")
with open("./User Guide.docx", "wb") as local_file:
    local_file.write(response.content)

In [282]:
ctx_auth = AuthenticationContext(url)
if ctx_auth.acquire_token_for_user(username, password):
    ctx = ClientContext(url, ctx_auth)
    filename = 'pc_codes.xlsx'
    with open(filename, 'wb') as output_file:
        response = File.open_binary(ctx, relative_url)
        output_file.write(response.content)
        print(response)
else:
  print(ctx_auth.get_last_error())

<Response [200]>

In [250]:
df_vendorline = pd.read_excel(save_file_name)

df_vim = pd.read_excel(vim_file_name, skiprows=4)

df_vendorline.drop(df_vendorline.tail(1).index, inplace = True)

df_vendorline['ReferenceKeyM'] = df_vendorline.ReferenceKey.apply(process_ref_key)

df_merged = pd.merge(df_vendorline, df_vim, left_on='ReferenceKeyM', right_on='DocumentNo', how='left')

df_merged['InvoiceProposal']=df_merged.apply(lambda x : process_ip_number(x),axis=1)

to_keep = ['VendorName', 'VendorID', 'CompanyCode', 'PaymentTerms', 'TXCode', 'Purch.Doc.', \
           'InvoiceProposal', 'DocumentNo_x', 'Reference_x', 'LCAmount', 'Currency', 'Status', \
           'DocType', 'ScheduledDate', 'Comment', 'ActionRequired']

df_merged.drop(df_merged.columns.difference(to_keep), axis=1, inplace=True)

df_merged.dropna(axis = 0, how = 'all', inplace = True)

df_merged['VendorName'] = vendor_name

df_merged = df_merged[to_keep]

df_merged.rename(columns={'VendorName': 'Vendor Name', 
                          'VendorID': 'Vendor ID',
                          'CompanyCode': 'Company Code',
                          'PaymentTerms': 'Payment Terms',
                          'TXCode': 'Tax Code',
                          'Purch.Doc.': 'Purchase Document',
                          'InvoiceProposal': 'Invoice Proposal',
                          'DocumentNo_x': 'Document Number',
                          'Reference_x': 'Invoice Reference',
                          'LCAmount': 'Net Value',
                          'Currency': 'Currency',
                          'Status': 'Status',
                          'DocType': 'Document Type',
                          # 'NetDueDate': 'Net Due Date',
                          'ScheduledDate': 'Payment Scheduled Date',
                          'Comment': 'Comment',
                          'ActionRequired': 'Action Required'}, inplace=True)

In [251]:

writer = pd.ExcelWriter(save_file_name) 
df_merged.to_excel(writer, sheet_name='PaymentStatus', index=False, na_rep='')

for column in df_merged:
    column_length = max(df_merged[column].astype(str).map(len).max(), len(column))
    col_idx = df_merged.columns.get_loc(column)
    # writer.sheets['PaymentStatus'].set_column(col_idx, col_idx, column_length)

writer.save()

In [252]:
fbl1n

NameError: name 'fbl1n' is not defined

In [277]:
import email
from openpyxl import load_workbook
import smtplib,ssl
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email.utils import formatdate
from email import encoders
from datetime import datetime
import re
import os
import sys
import numpy
import smtplib
import keyring
import pandas as pd


use_cmd_args = False
folder_location = r"C:\Users\40103611\Desktop\PMI_EUR_BOT_29"
fbl1n_file_name = r"C:\Users\40103611\Desktop\PMI_EUR_BOT_29\FBL1N_381111.xlsx"
vim_file_name = r"C:\Users\40103611\Desktop\PMI_EUR_BOT_29\VIM_Analytics_381111.xlsx"
save_file_name = r"C:\Users\40103611\Desktop\PMI_EUR_BOT_29\Status-381111-" + str(datetime.now().strftime("%Y-%m-%d-%H-%M-%S")) + ".xlsx"
log_file_name = r"C:\Users\40103611\Desktop\PMI_EUR_BOT_29\log_381111_405.txt"
vendor_id = 381111
vendor_type = 1
vendor_name = "ADM Spain"
pc_codes_file = r"C:\Users\40103611\Desktop\PMI_EUR_BOT_29\pc_codes.xlsx"
euz_scheduled_run_file = r"C:\Users\40103611\Desktop\PMI_EUR_BOT_29\EUZ_Scheduled_Run.xlsx"
vendor_email_address = 'vaibhav.vardhan@ab-inbev.com'

folder_location = '/Users/vsquareg/AbInBev'
fbl1n_file_name = os.path.join(folder_location, '0000381111_raw.xlsx')
save_file_name = os.path.join(folder_location, '0000381111_final.xlsx')
log_file_name = os.path.join(folder_location, '0000381111_log.txt')
vendor_id = '0000381111'
vendor_type = 4
pc_codes_file = os.path.join(folder_location, 'pc_codes.xlsx')
euz_scheduled_run_file = os.path.join(folder_location, 'EUZ_Scheduled_Run.xlsx')
vim_file_name = os.path.join(folder_location, 'VIM_Analytics_381111.xlsx')
vendor_name = 'ADM Spain'
vendor_email_address = os.path.join(folder_location, 'vaibhav.vardhan@ab-inbev.com')

if __name__ == "__main__" and use_cmd_args:
    folder_location = sys.argv[1]
    fbl1n_file_name = os.path.join(folder_location, sys.argv[2])
    save_file_name = os.path.join(folder_location, sys.argv[3])
    log_file_name = os.path.join(folder_location, sys.argv[4])
    vendor_id = sys.argv[5]
    vendor_type = sys.argv[6]
    pc_codes_file = os.path.join(folder_location, sys.argv[7])
    euz_scheduled_run_file = os.path.join(folder_location, sys.argv[8])
    vim_file_name = os.path.join(folder_location, sys.argv[9])
    vendor_email_address = sys.argv[10]
    vendor_name = sys.argv[11]


class Email:
    def __init__(self):
        self.client = smtplib.SMTP('smtp.gmail.com', 587)
  
        # start TLS for security
        self.client.starttls()

        # Authentication
        self.client.login("incupton@gmail.com", keyring.get_password('test_email', 'inc.upton@gmail.com'))

        self.from_email = "inc.upton@gmail.com"
        
    def send_email(self, to, subject, body, attachment = None):
        msg = MIMEMultipart()
        msg['From'] = self.from_email
        msg['To'] = to
        msg['Date'] = formatdate(localtime = True)
        msg['Subject'] = subject
        msg.attach(MIMEText(body))

        if attachment:
            fp = open(attachment, 'rb')
            part = MIMEBase('application','vnd.ms-excel')
            part.set_payload(fp.read())
            fp.close()
            encoders.encode_base64(part)
            part.add_header('Content-Disposition', 'attachment', filename=os.path.basename(attachment))
            msg.attach(part)

        self.client.sendmail(self.from_email, to, msg.as_string())

    def __del__(self):
        try:
            self.client.quit()
        except:
            pass
    
        
class Logger:
    def __init__(self, log_file_name, vendor_id):
        self.file = open(log_file_name, "a")
        self.vendor_id = vendor_id

    def add_log(self, err):
        self.file.write(' [ Execution for vendor ID: ' + str(self.vendor_id) + ' failed. ' + err + '] ')

    def __del__(self):
        self.file.close()

def process_ref_key(tmp):
    if not numpy.isnan(tmp):
        return int(tmp/10000)
    return tmp

def get(ws, col_name, row, value = True):
    if value:
        return ws.cell(row = row, column = columns[col_name]).value
    return ws.cell(row = row, column = columns[col_name])

def put(ws, col_name, row, val):
    ws.cell(row = row, column = columns[col_name]).value = val

def extract_PC_codes(pc_codes_file):
   workbook = load_workbook(filename=pc_codes_file)
   ws = workbook[workbook.sheetnames[0]]
   for row in ws.iter_rows(min_row = 2):
       pc_actions[row[0].value] = row[3].value
       pc_comments[row[0].value] = row[1].value

def handle_datetime(val):
    if 'datetime' not in str(type(val)):
        val = datetime.strptime(val, '%d/%m/%Y')
    return val
    
def extract_scheduled_dates(euz_scheduled_run_file):
    workbook = load_workbook(filename=euz_scheduled_run_file)
    ws = workbook[workbook.sheetnames[0]]
    for row in ws.iter_rows(min_row = 2):
        payment_dates.append(handle_datetime(row[0].value))
        cutoff_dates.append(handle_datetime(row[1].value))

def get_scheduled_date(baseline_date, vendor_type = 1):
    row_num = 12
    lowest_delta = 357
    scheduled_date = payment_dates[0]
    if vendor_type == 1:
        row_num = 12
    elif vendor_type == 2:
        row_num = 24
    elif vendor_type == 4:
        row_num = 48
    
    for row in range(row_num):
        now_delta = (payment_dates[row] - datetime.now()).days
        posting_delta = (cutoff_dates[row] - baseline_date).days
        # print(payment_dates[row], baseline_date, now_delta, posting_delta)
        if now_delta >= 0 and now_delta < lowest_delta and posting_delta >= 0:
            scheduled_date = payment_dates[row]
            lowest_delta = now_delta
    
    return scheduled_date.date()

def process_ip_number(x):
    if numpy.isnan(x['Purch.Doc.']):
        return float('nan')
    if numpy.isnan(x['Old DocNum']):
        return x['DocumentNo_y']
    else:
        return x['Old DocNum']

col_names = ['VendorID', 'PaymentBlock', 'DocType', 'CompanyCode', 'DocumentNo', 'Reference', 'PaymentTerms', 'Credit/Debit', 'LCAmount', 'Currency', 'TXCode', 'Text', 'BaselineDate', 'Status_V', 'Status', 'ReferenceKey', 'Comment', 'ActionRequired', 'ScheduledDate']

doctype = {
    'YE': 'Basware type',
    'RE': 'B2B/PDF',
    'KG': 'FI Credit Note',
    'KR': 'Credit Note',
    }

columns = {}
pc_actions = {}
pc_comments = {}
payment_dates = []
cutoff_dates = []

balance = {}


logger = Logger(log_file_name, vendor_id)
email_handler = Email()

import time
start = time.time()

for i, col in enumerate(col_names):
    columns[col] = i+1

try:
    extract_PC_codes(pc_codes_file)
except:
    logger.add_log('Unable to extract PC codes.')
    raise

try:
    extract_scheduled_dates(euz_scheduled_run_file)
except:
    logger.add_log('Unable to extract EUZ_Scheduled_Run')
    raise

begin_row = 1
begin_col = 1

try:
    workbook = load_workbook(filename=fbl1n_file_name)
    ws = workbook[workbook.sheetnames[0]]
except:
    logger.add_log('Unable to load VendorLine file.')
    raise

row_count = ws.max_row
# row_count = 40

for row in range(2, row_count + 1):
    
    # document type
    try:
        if curr_doc_type:= get(ws, 'DocType', row):
            put(ws, 'DocType', row, doctype[curr_doc_type])
    except:
        pass

    parked = False
    if get(ws, 'Status', row) == 'Parked':
        parked = True

    # payment block
    if get(ws, 'PaymentBlock', row):
        #TODO: add status check
        put(ws, 'Status', row, 'Blocked for ***')

    # mapping PC codes to comments/actions
    if text_str:= get(ws, 'Text', row):
        if pc_search:=re.search(r'(PC)\d\d',str(text_str)):
            pc_action = pc_actions[pc_search[0].upper()]
            pc_comment = pc_comments[pc_search[0].upper()]
            put(ws, 'Comment', row, pc_comment)
            put(ws, 'ActionRequired', row, pc_action)

    # getting scheduled date for non-parked items
    if not parked:
        try:
            if baseline_date:= get(ws, 'BaselineDate', row):
#                 baseline_date = datetime.strptime(baseline_date, '%d.%m.%Y')
                scheduled_date = get_scheduled_date(baseline_date, vendor_type)
                put(ws, 'ScheduledDate', row, scheduled_date)

                # update total balance for scheduled date
                amount_sgn = get(ws, 'Credit/Debit', row)
                amount = get(ws, 'LCAmount', row)
                
                if amount_sgn == 'H':
                    amount *= -1
#                 amount = get(ws, 'LCAmount', row).split(',')
#                 if len(amount) > 1:
#                     amount = float(amount[0].replace('.', '') + '.' + amount[1])
#                 else:
#                     amount = float(amount[0].replace('.', ''))
                balance[scheduled_date] = balance.get(scheduled_date, 0) + amount
        except Exception as e:
                print(e)
                put(ws, 'ScheduledDate', row, '')
    else:
        put(ws, 'ScheduledDate', row, '')

# debit-balance check; if debit balance, update status and scheduled date
for row in range(2, row_count + 1):
    if balance.get(get(ws, 'ScheduledDate', row), -1) >= 0:
        put(ws, 'Status', row, 'Debit balance')
        put(ws, 'ScheduledDate', row, '')

# rename columns
for col in col_names:
    put(ws, col, 1, col)

# delete unnecessary columns
# to_delete = ['ReferenceKey', 'BaselineDate', 'PCAmount', 'Text','PaymentBlock']
to_delete = ['Status_V', 'Text', 'PaymentBlock']

for col in to_delete:
    ws.delete_cols(columns[col], 1)

try:
    workbook.save(filename = save_file_name)
except:
    logger.add_log('Unable to save modified VendorLine file.')

FileNotFoundError: [Errno 2] No such file or directory: '/Users/vsquareg/AbInBev/0000381111_raw.xlsx'

In [256]:
df_vendorline = pd.read_excel(save_file_name)

df_vim = pd.read_excel(vim_file_name, skiprows=4)

df_vendorline.drop(df_vendorline.tail(1).index, inplace = True)

df_vendorline['ReferenceKeyM'] = df_vendorline.ReferenceKey.apply(process_ref_key)

df_merged = pd.merge(df_vendorline, df_vim, left_on='ReferenceKeyM', right_on='DocumentNo', how='left')

df_merged['InvoiceProposal']=df_merged.apply(lambda x : process_ip_number(x),axis=1)

to_keep = ['VendorName', 'VendorID', 'CompanyCode', 'PaymentTerms', 'TXCode', 'Purch.Doc.', \
           'InvoiceProposal', 'DocumentNo_x', 'Reference_x', 'LCAmount', 'Currency', 'Status', \
           'DocType', 'ScheduledDate', 'Comment', 'ActionRequired', 'ReferenceKeyM']

df_merged.drop(df_merged.columns.difference(to_keep), axis=1, inplace=True)

df_merged.dropna(axis = 0, how = 'all', inplace = True)

df_merged['VendorName'] = vendor_name

df_merged = df_merged[to_keep]

df_merged.rename(columns={'VendorName': 'Vendor Name', 
                          'VendorID': 'Vendor ID',
                          'CompanyCode': 'Company Code',
                          'PaymentTerms': 'Payment Terms',
                          'TXCode': 'Tax Code',
                          'Purch.Doc.': 'Purchase Document',
                          'InvoiceProposal': 'Invoice Proposal',
                          'DocumentNo_x': 'Document Number',
                          'Reference_x': 'Invoice Reference',
                          'LCAmount': 'Net Value',
                          'Currency': 'Currency',
                          'Status': 'Status',
                          'DocType': 'Document Type',
                          # 'NetDueDate': 'Net Due Date',
                          'ScheduledDate': 'Payment Scheduled Date',
                          'Comment': 'Comment',
                          'ActionRequired': 'Action Required'
                          'ReferenceKeyM': 'ReferenceKeyM'
                         }, inplace=True)


# writer = pd.ExcelWriter(save_file_name) 
# df_merged.to_excel(writer, sheet_name='PaymentStatus', index=False, na_rep='')

# for column in df_merged:
#     column_length = max(df_merged[column].astype(str).map(len).max(), len(column))
#     col_idx = df_merged.columns.get_loc(column)
#     # writer.sheets['PaymentStatus'].set_column(col_idx, col_idx, column_length)

# writer.save()

# print(time.time() - start)

# # email_address = "vaibhav.vardhan@ab-inbev.com"
# # email_handler.send_email("vaibhav.vardhan@ab-inbev.com", "Hola", "From python", save_file_name)

# # print(time.time() - start)

In [259]:
df_vim

,Unnamed: 0,Document Id,CoCd,DocumentNo,DOC status,Exception Reason,Type,Reference,Vendor,CreditMemo,Vendor Nam,Purch.Doc.,TotalAmoun,DocCurrenc,Doc. Date,Pst Date,Due Date,Old DocNum
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1.000040e+11,GB11,5.112838e+09,Posted,NaN,YE,IABESP01000204,381111.0,NaN,ADM Spain,4.505356e+09,"16.688,10",GBP,25.02.2020,15.01.2021,30.06.2020,NaN
2,NaN,1.000040e+11,GB11,5.112838e+09,Posted,NaN,YE,IABESP01000204,381111.0,X,ADM Spain,4.505356e+09,"13.906,75",GBP,10.12.2019,15.01.2021,10.12.2019,NaN
3,NaN,1.000040e+11,GB11,5.112838e+09,Posted,NaN,YE,IABESP01000346,381111.0,NaN,ADM Spain,4.505550e+09,"11.184,00",GBP,01.05.2020,15.01.2021,30.09.2020,NaN
4,NaN,1.000040e+11,GB11,5.112838e+09,Posted,NaN,YE,IABESP01000346,381111.0,X,ADM Spain,4.505550e+09,"9.320,00",GBP,20.03.2020,15.01.2021,20.03.2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468,NaN,NaN,BE11,5.112184e+09,Posted,NaN,YE,IABESP01000219B,381111.0,NaN,ADM Spain,4.505466e+09,"5.940,00",EUR,02.03.2020,02.03.2020,31.08.2020,NaN
469,NaN,NaN,BE11,5.112182e+09,Posted,NaN,YE,IABESP01000219A,381111.0,NaN,ADM Spain,4.505466e+09,"11.790,00",EUR,02.03.2020,02.03.2020,31.08.2020,NaN
470,NaN,NaN,BE11,5.112111e+09,Posted,NaN,YE,IABESP01000266,381111.0,NaN,ADM Spain,4.505407e+09,"1.953,00",EUR,25.03.2020,25.03.2020,31.07.2020,NaN
471,NaN,NaN,BE11,5.112092e+09,Posted,NaN,YE,IABESP01000211,381111.0,NaN,ADM Spain,4.505394e+09,"1.439,00",EUR,27.02.2020,27.02.2020,30.06.2020,5.112080e+09
472,NaN,NaN,BE11,5.112088e+09,Posted,NaN,YE,IABESP01000043,381111.0,NaN,ADM Spain,4.505240e+09,"21.458,90",EUR,17.01.2020,17.01.2020,30.04.2020,5.111918e+09

In [260]:
import pandas
import pyodbc
import os
import subprocess
start = time.time()
cnxn = pyodbc.connect("DRIVER={ODBC Driver 17 for SQL Server};SERVER=edhazurencertdmgbprod.database.windows.net;PORT=1433;DATABASE=edhazurencertdmgbprod;UID=BOT_PMI_PaymentPlanEUR@ab-inbev.com;PWD=3]TF9+T7mqa5_\j,[F+3nY{z7@'n3m[};AUTHENTICATION=ActiveDirectoryPassword")

In [261]:
sql = "SELECT lifnr, bukrs, belnr, shkzg, dmbtr, mwskz, sgtxt FROM [abi_compliance_control_europe_non_sensitive_rpt].[bseg] WHERE lifnr = '0000381111' AND bukrs = 'FR11'"
tmp = pandas.read_sql(sql,cnxn)
tmp

           lifnr bukrs       belnr shkzg    dmbtr mwskz sgtxt
0     0000381111  FR11  5000038877     S  18040.0
1     0000381111  FR11  0100012522     S   6098.0
2     0000381111  FR11  5000035887     S  12656.0
3     0000381111  FR11  5000011154     S  29293.0
4     0000381111  FR11  5000011154     H   5271.0
...          ...   ...         ...   ...      ...   ...   ...
1111  0000381111  FR11  5000014653     S   2400.3
1112  0000381111  FR11  5000029129     S   2061.0
1113  0000381111  FR11  5000029129     H   2061.0
1114  0000381111  FR11  5000021620     S   3197.0
1115  0000381111  FR11  5000029125     S   1947.6

[1116 rows x 7 columns]

In [263]:
len(tmp.belnr.unique())

448

In [265]:
tmp1 = ['5100006898', '5100006419', '5100006242', '5100006306',
       '5100011514', '5100009579', '5100005275', '5100011219',
       '5100006320', '5100009213', '5100007921', '5100012417',
       '5100006117', '5100005945', '5100009578', '5100007635',
       '5100005910', '5100005270', '5100005274', '5100008968',
       '5100003280', '5100012005', '5100006561', '5100012796',
       '5100012794', '5100010429', '5100005415', '5100008085',
       '5100012006', '5100008965', '5100012988', '5100000257',
       '5100007494', '5100009380']

In [267]:
for bel in tmp1:
    if bel not in tmp.belnr.unique():
        print(bel)

5100006242
5100012005
5100012794
5100012006

In [278]:
extract_scheduled_dates('/Users/vsquareg/AbInBev/EUZ_Scheduled_Run.xlsx')

In [279]:
payment_dates

[datetime.datetime(2021, 1, 4, 0, 0),
 datetime.datetime(2021, 2, 3, 0, 0),
 datetime.datetime(2021, 3, 3, 0, 0),
 datetime.datetime(2021, 4, 6, 0, 0),
 datetime.datetime(2021, 5, 3, 0, 0),
 datetime.datetime(2021, 6, 3, 0, 0),
 datetime.datetime(2021, 7, 5, 0, 0),
 datetime.datetime(2021, 8, 3, 0, 0),
 datetime.datetime(2021, 9, 3, 0, 0),
 datetime.datetime(2021, 10, 4, 0, 0),
 datetime.datetime(2021, 11, 3, 0, 0),
 datetime.datetime(2021, 12, 3, 0, 0),
 datetime.datetime(2021, 1, 18, 0, 0),
 datetime.datetime(2021, 2, 17, 0, 0),
 datetime.datetime(2021, 3, 17, 0, 0),
 datetime.datetime(2021, 4, 19, 0, 0),
 datetime.datetime(2021, 5, 17, 0, 0),
 datetime.datetime(2021, 6, 17, 0, 0),
 datetime.datetime(2021, 7, 19, 0, 0),
 datetime.datetime(2021, 8, 17, 0, 0),
 datetime.datetime(2021, 9, 17, 0, 0),
 datetime.datetime(2021, 10, 18, 0, 0),
 datetime.datetime(2021, 11, 17, 0, 0),
 datetime.datetime(2021, 12, 17, 0, 0),
 datetime.datetime(2021, 1, 11, 0, 0),
 datetime.datetime(2021, 2, 10, 0, 0),
 datetime.datetime(2021, 3, 10, 0, 0),
 datetime.datetime(2021, 4, 12, 0, 0),
 datetime.datetime(2021, 5, 11, 0, 0),
 datetime.datetime(2021, 6, 10, 0, 0),
 datetime.datetime(2021, 7, 12, 0, 0),
 datetime.datetime(2021, 8, 10, 0, 0),
 datetime.datetime(2021, 9, 10, 0, 0),
 datetime.datetime(2021, 10, 11, 0, 0),
 datetime.datetime(2021, 11, 10, 0, 0),
 datetime.datetime(2021, 12, 10, 0, 0),
 datetime.datetime(2021, 1, 25, 0, 0),
 datetime.datetime(2021, 2, 24, 0, 0),
 datetime.datetime(2021, 3, 24, 0, 0),
 datetime.datetime(2021, 4, 26, 0, 0),
 datetime.datetime(2021, 5, 24, 0, 0),
 datetime.datetime(2021, 6, 24, 0, 0),
 datetime.datetime(2021, 7, 26, 0, 0),
 datetime.datetime(2021, 8, 24, 0, 0),
 datetime.datetime(2021, 9, 24, 0, 0),
 datetime.datetime(2021, 10, 25, 0, 0),
 datetime.datetime(2021, 11, 24, 0, 0),
 datetime.datetime(2021, 12, 24, 0, 0),
 datetime.datetime(2021, 1, 4, 0, 0),
 datetime.datetime(2021, 2, 3, 0, 0),
 datetime.datetime(2021, 3, 3, 0, 0),
 datetime.datetime(2021, 4, 6, 0, 0),
 datetime.datetime(2021, 5, 3, 0, 0),
 datetime.datetime(2021, 6, 3, 0, 0),
 datetime.datetime(2021, 7, 5, 0, 0),
 datetime.datetime(2021, 8, 3, 0, 0),
 datetime.datetime(2021, 9, 3, 0, 0),
 datetime.datetime(2021, 10, 4, 0, 0),
 datetime.datetime(2021, 11, 3, 0, 0),
 datetime.datetime(2021, 12, 3, 0, 0),
 datetime.datetime(2021, 1, 18, 0, 0),
 datetime.datetime(2021, 2, 17, 0, 0),
 datetime.datetime(2021, 3, 17, 0, 0),
 datetime.datetime(2021, 4, 19, 0, 0),
 datetime.datetime(2021, 5, 17, 0, 0),
 datetime.datetime(2021, 6, 17, 0, 0),
 datetime.datetime(2021, 7, 19, 0, 0),
 datetime.datetime(2021, 8, 17, 0, 0),
 datetime.datetime(2021, 9, 17, 0, 0),
 datetime.datetime(2021, 10, 18, 0, 0),
 datetime.datetime(2021, 11, 17, 0, 0),
 datetime.datetime(2021, 12, 17, 0, 0),
 datetime.datetime(2021, 1, 11, 0, 0),
 datetime.datetime(2021, 2, 10, 0, 0),
 datetime.datetime(2021, 3, 10, 0, 0),
 datetime.datetime(2021, 4, 12, 0, 0),
 datetime.datetime(2021, 5, 11, 0, 0),
 datetime.datetime(2021, 6, 10, 0, 0),
 datetime.datetime(2021, 7, 12, 0, 0),
 datetime.datetime(2021, 8, 10, 0, 0),
 datetime.datetime(2021, 9, 10, 0, 0),
 datetime.datetime(2021, 10, 11, 0, 0),
 datetime.datetime(2021, 11, 10, 0, 0),
 datetime.datetime(2021, 12, 10, 0, 0),
 datetime.datetime(2021, 1, 25, 0, 0),
 datetime.datetime(2021, 2, 24, 0, 0),
 datetime.datetime(2021, 3, 24, 0, 0),
 datetime.datetime(2021, 4, 26, 0, 0),
 datetime.datetime(2021, 5, 24, 0, 0),
 datetime.datetime(2021, 6, 24, 0, 0),
 datetime.datetime(2021, 7, 26, 0, 0),
 datetime.datetime(2021, 8, 24, 0, 0),
 datetime.datetime(2021, 9, 24, 0, 0),
 datetime.datetime(2021, 10, 25, 0, 0),
 datetime.datetime(2021, 11, 24, 0, 0),
 datetime.datetime(2021, 12, 24, 0, 0)]

In [280]:
cutoff_dates

[datetime.datetime(2020, 12, 28, 0, 0),
 datetime.datetime(2021, 1, 27, 0, 0),
 datetime.datetime(2021, 2, 24, 0, 0),
 datetime.datetime(2021, 3, 30, 0, 0),
 datetime.datetime(2021, 4, 26, 0, 0),
 datetime.datetime(2021, 5, 27, 0, 0),
 datetime.datetime(2021, 6, 28, 0, 0),
 datetime.datetime(2021, 7, 27, 0, 0),
 datetime.datetime(2021, 8, 27, 0, 0),
 datetime.datetime(2021, 9, 27, 0, 0),
 datetime.datetime(2021, 10, 27, 0, 0),
 datetime.datetime(2021, 11, 26, 0, 0),
 datetime.datetime(2021, 1, 11, 0, 0),
 datetime.datetime(2021, 2, 10, 0, 0),
 datetime.datetime(2021, 3, 10, 0, 0),
 datetime.datetime(2021, 4, 12, 0, 0),
 datetime.datetime(2021, 5, 10, 0, 0),
 datetime.datetime(2021, 6, 10, 0, 0),
 datetime.datetime(2021, 7, 12, 0, 0),
 datetime.datetime(2021, 8, 10, 0, 0),
 datetime.datetime(2021, 9, 10, 0, 0),
 datetime.datetime(2021, 10, 11, 0, 0),
 datetime.datetime(2021, 11, 10, 0, 0),
 datetime.datetime(2021, 12, 10, 0, 0),
 datetime.datetime(2021, 1, 4, 0, 0),
 datetime.datetime(2021, 2, 3, 0, 0),
 datetime.datetime(2021, 3, 3, 0, 0),
 datetime.datetime(2021, 4, 5, 0, 0),
 datetime.datetime(2021, 5, 4, 0, 0),
 datetime.datetime(2021, 6, 3, 0, 0),
 datetime.datetime(2021, 7, 5, 0, 0),
 datetime.datetime(2021, 8, 3, 0, 0),
 datetime.datetime(2021, 9, 3, 0, 0),
 datetime.datetime(2021, 10, 4, 0, 0),
 datetime.datetime(2021, 11, 3, 0, 0),
 datetime.datetime(2021, 12, 3, 0, 0),
 datetime.datetime(2021, 1, 18, 0, 0),
 datetime.datetime(2021, 2, 17, 0, 0),
 datetime.datetime(2021, 3, 17, 0, 0),
 datetime.datetime(2021, 4, 19, 0, 0),
 datetime.datetime(2021, 5, 17, 0, 0),
 datetime.datetime(2021, 6, 17, 0, 0),
 datetime.datetime(2021, 7, 19, 0, 0),
 datetime.datetime(2021, 8, 17, 0, 0),
 datetime.datetime(2021, 9, 17, 0, 0),
 datetime.datetime(2021, 10, 18, 0, 0),
 datetime.datetime(2021, 11, 17, 0, 0),
 datetime.datetime(2021, 12, 17, 0, 0),
 datetime.datetime(2020, 12, 28, 0, 0),
 datetime.datetime(2021, 1, 27, 0, 0),
 datetime.datetime(2021, 2, 24, 0, 0),
 datetime.datetime(2021, 3, 30, 0, 0),
 datetime.datetime(2021, 4, 26, 0, 0),
 datetime.datetime(2021, 5, 27, 0, 0),
 datetime.datetime(2021, 6, 28, 0, 0),
 datetime.datetime(2021, 7, 27, 0, 0),
 datetime.datetime(2021, 8, 27, 0, 0),
 datetime.datetime(2021, 9, 27, 0, 0),
 datetime.datetime(2021, 10, 27, 0, 0),
 datetime.datetime(2021, 11, 26, 0, 0),
 datetime.datetime(2021, 1, 11, 0, 0),
 datetime.datetime(2021, 2, 10, 0, 0),
 datetime.datetime(2021, 3, 10, 0, 0),
 datetime.datetime(2021, 4, 12, 0, 0),
 datetime.datetime(2021, 5, 10, 0, 0),
 datetime.datetime(2021, 6, 10, 0, 0),
 datetime.datetime(2021, 7, 12, 0, 0),
 datetime.datetime(2021, 8, 10, 0, 0),
 datetime.datetime(2021, 9, 10, 0, 0),
 datetime.datetime(2021, 10, 11, 0, 0),
 datetime.datetime(2021, 11, 10, 0, 0),
 datetime.datetime(2021, 12, 10, 0, 0),
 datetime.datetime(2021, 1, 4, 0, 0),
 datetime.datetime(2021, 2, 3, 0, 0),
 datetime.datetime(2021, 3, 3, 0, 0),
 datetime.datetime(2021, 4, 5, 0, 0),
 datetime.datetime(2021, 5, 4, 0, 0),
 datetime.datetime(2021, 6, 3, 0, 0),
 datetime.datetime(2021, 7, 5, 0, 0),
 datetime.datetime(2021, 8, 3, 0, 0),
 datetime.datetime(2021, 9, 3, 0, 0),
 datetime.datetime(2021, 10, 4, 0, 0),
 datetime.datetime(2021, 11, 3, 0, 0),
 datetime.datetime(2021, 12, 3, 0, 0),
 datetime.datetime(2021, 1, 18, 0, 0),
 datetime.datetime(2021, 2, 17, 0, 0),
 datetime.datetime(2021, 3, 17, 0, 0),
 datetime.datetime(2021, 4, 19, 0, 0),
 datetime.datetime(2021, 5, 17, 0, 0),
 datetime.datetime(2021, 6, 17, 0, 0),
 datetime.datetime(2021, 7, 19, 0, 0),
 datetime.datetime(2021, 8, 17, 0, 0),
 datetime.datetime(2021, 9, 17, 0, 0),
 datetime.datetime(2021, 10, 18, 0, 0),
 datetime.datetime(2021, 11, 17, 0, 0),
 datetime.datetime(2021, 12, 17, 0, 0)]