# Data Owner

### Let's see our dataset

In [1]:
import pandas as pd

In [2]:
canada_dataset = pd.read_csv("ca - feb 2021.csv")

/tmp/ipykernel_277845/2814267858.py:1: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  canada_dataset = pd.read_csv("ca - feb 2021.csv")

In [3]:
canada_dataset.shape

(227454, 22)

In [4]:
canada_dataset.head()

,Classification,Year,Period,Period Desc.,Aggregate Level,Is Leaf Code,Trade Flow Code,Trade Flow,Reporter Code,Reporter,...,Partner,Partner ISO,Commodity Code,Commodity,Qty Unit Code,Qty Unit,Qty,Netweight (kg),Trade Value (US$),Flag
0,HS,2021,202102,February 2021,4,0,1,Imports,124,Canada,...,"Other Asia, nes",NaN,6117,"Clothing accessories; made up, knitted or croc...",0,NaN,NaN,NaN,9285,0
1,HS,2021,202102,February 2021,2,0,1,Imports,124,Canada,...,Egypt,NaN,18,Cocoa and cocoa preparations,0,NaN,NaN,0.0,116604,0
2,HS,2021,202102,February 2021,2,0,1,Imports,124,Canada,...,United Kingdom,NaN,18,Cocoa and cocoa preparations,0,NaN,NaN,0.0,1495175,0
3,HS,2021,202102,February 2021,2,0,1,Imports,124,Canada,...,United Rep. of Tanzania,NaN,18,Cocoa and cocoa preparations,0,NaN,NaN,0.0,2248,0
4,HS,2021,202102,February 2021,2,0,1,Imports,124,Canada,...,Singapore,NaN,18,Cocoa and cocoa preparations,0,NaN,NaN,0.0,47840,0

In [5]:
canada_dataset.columns

Index(['Classification', 'Year', 'Period', 'Period Desc.', 'Aggregate Level',
       'Is Leaf Code', 'Trade Flow Code', 'Trade Flow', 'Reporter Code',
       'Reporter', 'Reporter ISO', 'Partner Code', 'Partner', 'Partner ISO',
       'Commodity Code', 'Commodity', 'Qty Unit Code', 'Qty Unit', 'Qty',
       'Netweight (kg)', 'Trade Value (US$)', 'Flag'],
      dtype='object')

In [6]:
canada_dataset['Trade Flow'].unique()

array(['Imports', 'Exports', 'Re-exports', 'Re-imports'], dtype=object)

In [7]:
canada_dataset[canada_dataset['Trade Flow'] == "Imports"]

,Classification,Year,Period,Period Desc.,Aggregate Level,Is Leaf Code,Trade Flow Code,Trade Flow,Reporter Code,Reporter,...,Partner,Partner ISO,Commodity Code,Commodity,Qty Unit Code,Qty Unit,Qty,Netweight (kg),Trade Value (US$),Flag
0,HS,2021,202102,February 2021,4,0,1,Imports,124,Canada,...,"Other Asia, nes",NaN,6117,"Clothing accessories; made up, knitted or croc...",0,NaN,NaN,NaN,9285,0
1,HS,2021,202102,February 2021,2,0,1,Imports,124,Canada,...,Egypt,NaN,18,Cocoa and cocoa preparations,0,NaN,NaN,0.0,116604,0
2,HS,2021,202102,February 2021,2,0,1,Imports,124,Canada,...,United Kingdom,NaN,18,Cocoa and cocoa preparations,0,NaN,NaN,0.0,1495175,0
3,HS,2021,202102,February 2021,2,0,1,Imports,124,Canada,...,United Rep. of Tanzania,NaN,18,Cocoa and cocoa preparations,0,NaN,NaN,0.0,2248,0
4,HS,2021,202102,February 2021,2,0,1,Imports,124,Canada,...,Singapore,NaN,18,Cocoa and cocoa preparations,0,NaN,NaN,0.0,47840,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129739,HS,2021,202102,February 2021,6,1,1,Imports,124,Canada,...,Croatia,NaN,851590,"Welding, brazing or soldering machines; parts ...",0,NaN,NaN,NaN,32,0
129740,HS,2021,202102,February 2021,6,1,1,Imports,124,Canada,...,Czech Rep.,NaN,851590,"Welding, brazing or soldering machines; parts ...",0,NaN,NaN,NaN,49428,0
129741,HS,2021,202102,February 2021,6,1,1,Imports,124,Canada,...,Denmark,NaN,851590,"Welding, brazing or soldering machines; parts ...",0,NaN,NaN,NaN,911,0
129742,HS,2021,202102,February 2021,6,1,1,Imports,124,Canada,...,Estonia,NaN,851590,"Welding, brazing or soldering machines; parts ...",0,NaN,NaN,NaN,606,0
129743,HS,2021,202102,February 2021,6,1,1,Imports,124,Canada,...,Finland,NaN,851590,"Welding, brazing or soldering machines; parts ...",0,NaN,NaN,NaN,87,0

### Annotate Data

In [8]:
imports = canada_dataset[canada_dataset['Trade Flow'] == "Imports"]
exports = canada_dataset[canada_dataset['Trade Flow'] == "Exports"]

In [9]:
imports_value = imports['Trade Value (US$)'].to_numpy()
exports_value = exports['Trade Value (US$)'].to_numpy()

In [10]:
importers = imports["Partner"]
exporters = exports["Partner"]

In [12]:
import syft as sy

/home/e/anaconda3/envs/Hagrid/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [13]:
imports_data = sy.Tensor(child=imports_value).private(min_val=0, max_val=2e12, data_subjects=importers)
exports_data = sy.Tensor(child=exports_value).private(min_val=0, max_val=2e12, data_subjects=exporters)

### Log Into Our Domain Node

In [14]:
import syft as sy
import numpy as np

In [15]:
domain = sy.login(email="info@openmined.org", password="changethis", port=8081)

WARNING: CHANGE YOUR USERNAME AND PASSWORD!!!

Anyone can login as an admin to your node right now because your password is still the default PySyft username and password!!!

Connecting to localhost... done! 	 Logging into adp... done!

In [16]:
domain.load_dataset(
    assets={
        "imports": imports_data,
        "exports": exports_data
    }, name="Canada Imports and Exports Feb 2021", 
    description="This dataset contains information about all of Canada's imports and exports\
    in the month of Feb 2021. Measured in USD."
)

kj/filesystem-disk-unix.c++:1690: warning: PWD environment variable doesn't match current directory; pwd = /home/e/PycharmProjects/PySyft/notebooks/petlab_sessions

Loading dataset... uploading...ðŸš€

Uploading `imports`: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:00<00:00, 114.09it/s]
Uploading `exports`: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:00<00:00, 113.82it/s]

Dataset is uploaded successfully !!! ðŸŽ‰

Run `<your client variable>.datasets` to see your new dataset loaded into your machine!

In [17]:
domain.datasets

In [18]:
domain.create_user(
    name="Ishan Mishra", 
    email="ishan@openmined.org", 
    password="too_many_puns.gif", 
    budget=10
)

User created successfully!

{'name': 'Ishan Mishra',
 'email': 'ishan@openmined.org',
 'password': 'too_many_puns.gif',
 'url': 'localhost'}